### ISSUE TITLE
Config files and dynamic input params don't seem to cooperate

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2galaxy#1]
Given this xml:
```xml
   <command>q2galaxy run diversity pcoa '$inputs'</command>
   <configfiles>
      <inputs name="inputs"/>
   </configfiles>
   <inputs>
      <param name="example" type="integer" value="0" />
      <param format="qza" help="The distance matrix on which PCoA should be computed." name="distance_matrix" type="data">
         <options options_filter_attribute="metadata.semantic_type">
            <filter type="add_value" value="DistanceMatrix"/>
         </options>
      </param>
   </inputs>
```

The `$inputs` file is not including a key/value pair for `distance_matrix`. This could be related to my patch https://github.com/galaxyproject/galaxy/pull/6443, or perhaps this has never quite worked right with `options_filter_attribute`/filter on data-params.

In any case, we have two options:

1. fix the config file in galaxy (probably the right way to do this)
2. actually make a command line interface for galaxy with key/value pairs

I'm definitely leaning towards option 1 and I'll see what I can dig up inside galaxy for why this might be happening.

cc @bgruening

**Comment by ebolyen** [comment]
Figured out why this is happening. It looks like `<param type="data">` is intentionally excluded. I was able to confirm this with a simple param of type data (no filtering).

Here's the code path:
[`__build_config_file_text`](https://github.com/galaxyproject/galaxy/blob/cc0022d5d1cc985b23644b6ff6b3e60c29d9caa6/lib/galaxy/tools/evaluation.py#L569)
[`json_wrap`](https://github.com/galaxyproject/galaxy/blob/cc0022d5d1cc985b23644b6ff6b3e60c29d9caa6/lib/galaxy/tools/parameters/wrapped_json.py#L15)
[`_json_wrap_input`](https://github.com/galaxyproject/galaxy/blob/cc0022d5d1cc985b23644b6ff6b3e60c29d9caa6/lib/galaxy/tools/parameters/wrapped_json.py#L46-L53)

If we trace `handle_files` we see there's no way to override the behavior, which is to `"SKIP"`.

Follow up question:

Should there be a mechanism to request inputs of type data as well? Hypothetical XML:
```xml
<configfiles>
   <inputs name="inputs" include_data="true" />
</configfiles>
```

It looks like there was some intention for permitting files though the json config, but the machinery was just never implemented.

**Comment by ebolyen** [comment]
@blankenberg should I just proceed with option 2 at this point? Seems easiest, I could still use the config for QIIME 2 parameters. QIIME 2 inputs would just become simple key/value pairs on the q2galaxy interface.

**Comment by bgruening** [comment]
@jmchilton do you know why data prams are not included?

**Comment by jmchilton** [comment]
> It looks like there was some intention for permitting files though the json config, but the machinery was just never implemented.

Yeah - I just wasn't sure what the interface should be in this case. Simply including the path in the dict would be an option but there is potentially valuable metadata not included then. 

```json
{
  "input": "/path/to/dataset"
}
```

vs.

```json
{
   "input": { 
      "class": "File",
      "name": "My Dataset",
      "path": "/path/to/dataset",
      "ext": "fastq",
      "extra_files_path": "/path/to/extra_files",
}
```

I became paralyzed by options and didn't want to commit to anything and so I moved on. Maybe I'll open a PR to add say... ``data_style="path"``... to force the first option. Seems like it would be enough for here right?

**Comment by blankenberg** [comment]
I've generally built the json directly myself, or made use of e.g. `tool_type=output_parameter_json` or `tool_type=data_source`, but it looks like https://github.com/galaxyproject/galaxy/pull/6468 is on a good path to get this done for you?

**Comment by ebolyen** [comment]
@jmchilton, makes sense! And yes, path should be sufficient for this application.

@blankenberg, yep it looks like everything is a few PRs away from working. Now I just need to address the QIIME 2 metadata format and see if I can get that to play well with other tabular datasets :)

**Comment by blankenberg** [comment]
Awesome, please let me know if there is anything else I can do to help, or if a quick call/skype/hangout would be beneficial. Really excited to have this nice coupling of QIIME2 and Galaxy!

**Comment by ebolyen** [comment]
Closing as I can confirm https://github.com/galaxyproject/galaxy/pull/6468 fixes the issue!
