### ISSUE TITLE
ToolShed deposit

### ISSUE THREAD

**Issue by abretaud** [qiime2/q2galaxy#37]
Hi,
I've seen several people asking to install Qiime2 on different Galaxy usegalaxy.* servers.
What I see on this repo is interesting but it seems like it's not possible to install the tools the "standard way" from the ToolShed. Is this planned at some point on your roadmap?

**Comment by abretaud** [comment]
Hi
Ok, good to know that you have this goal in mind :)
I don't have much bandwidth to help at the code level at the moment, but if you have questions, I or anyone from [IUC](https://github.com/galaxyproject/tools-iuc/) can probably help (I don't know if you're in contact with anyone there yet)

**Comment by ebolyen** [comment]
Sounds good, currently in touch with @blankenberg, @bgruening, and a few other folks. Hopefully I can make some reasonable progress on the distribution side of things soon!

**Comment by ebolyen** [comment]
Tracking for this is now in a prototype toolshed repo: https://github.com/qiime2/galaxy-tools/issues
