### ISSUE TITLE
Create <sections> for inputs, parameters, and collapse default/optional inputs/params

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2galaxy#4]
**References**
Using this: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-section

**Comment by blankenberg** [comment]
Sections are nice, just be aware that there isn't necessarily an easy way to check if anything in a section has been changed, so you'll need to always pass the values down (even when a default). Not necessarily a problem when the form defaults match the command default behavior, but just something to be aware of. 

Often times, especially in cases when we only want to pass values when a user 'activates' a 'section', we'll use Conditionals to hide 'advanced options', which you can then test to see if 'expanded' and only pass values if it is: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-conditional

But sections are great for hiding things by default that will always be passed. Another point of note is that currently if a section is defined to not be expanded by default, it won't be expanded automatically when using rerun even if a setting under it was changed from the default, so some changes can be somewhat hidden -- I'd consider this a UI wart though, and hopefully it will change in the future at some point.
