### ISSUE TITLE
qiime2_core__tools__import stacktrace from usegalaxy.eu

### ISSUE THREAD

**Issue by bgruening** [qiime2/q2galaxy#46]
Hi,

we got this error report, let me know if you need more information.

Thanks for this great tool suite!

Tool ID: toolshed.g2.bx.psu.edu/repos/q2d2/qiime2_core__tools__import/qiime2_core__tools__import/2022.11.1+dist.h2bda5906.2

Error: 

```
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 291, in prepare_job
    job_wrapper.prepare()
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1254, in prepare
    ) = tool_evaluator.build()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 566, in build
    global_tool_logs(self._build_config_files, config_file, "Building Config Files")
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 96, in global_tool_logs
    raise e
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 92, in global_tool_logs
    return func()
           ^^^^^^
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 633, in _build_config_files
    self.__write_workdir_file(config_filename, config_text, param_dict, is_template=is_template)
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 756, in __write_workdir_file
    value = fill_template(content, context=context, python_template_version=self.tool.python_template_version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/galaxy/server/lib/galaxy/util/template.py", line 143, in fill_template
    raise first_exception or e
  File "/opt/galaxy/server/lib/galaxy/util/template.py", line 87, in fill_template
    return unicodify(t, log_exception=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/galaxy/server/lib/galaxy/util/__init__.py", line 1153, in unicodify
    value = str(value)
            ^^^^^^^^^^
  File "/opt/galaxy/venv/lib/python3.11/site-packages/Cheetah/Template.py", line 1053, in __unicode__
    return getattr(self, mainMethName)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cheetah_DynamicallyCompiledCheetahTemplate_1699011302_5547879_70105.py", line 119, in respond
  File "cheetah_DynamicallyCompiledCheetahTemplate_1699011302_5547879_70105.py", line 102, in stringify
  File "cheetah_DynamicallyCompiledCheetahTemplate_1699011302_5547879_70105.py", line 113, in stringify
AttributeError: 'TreeDict' object has no attribute 'is_collection'
```

**Comment by ebolyen** [comment]
Thanks @bgruening!

What version of Galaxy was this error found on?

My hunch is this either is a dropped-ball with the new `collection` stuff in QIIME 2, or we were doing naughty things with the Cheetah templates, and it's finally caught up to us. Or maybe it's both.

**Comment by ebolyen** [comment]
Found the answer to my own question here: https://usegalaxy.eu/about

**Comment by bgruening** [comment]
:-)

**Comment by ebolyen** [comment]
Looks like it's the latter:
https://github.com/qiime2/q2galaxy/blob/dev/q2galaxy/core/templaters/import_data.py#L287

Also, if the `is_collection` attr doesn't exist, then we were about to fall off the known cases for our custom stringify, so we need to probably adapt how we handle this. 

Inspecting the result of: https://github.com/qiime2/q2galaxy/blob/dev/q2galaxy/core/templaters/import_data.py#L292
will probably help.

**Comment by ebolyen** [comment]
We may also be able to use the more modern `staging_path_and_source_path` style for the config, which would mean we could ditch our gross dynamic config.

**Comment by bernt-matthias** [comment]
ant progress here? 

see also https://github.com/qiime2/galaxy-tools/pull/51

**Comment by bernt-matthias** [comment]
Note that all usegalaxy servers are now 23.1 or later, i.e. qiime2 on Galaxy is currently broken.

**Comment by bernt-matthias** [comment]
https://github.com/qiime2/galaxy-tools/pull/51/commits/87b8fb15213897e207b26bf244772dd7e3c62146 shows that `staging_path_and_source_path` should work.

**Comment by Oddant1** [comment]
@bernt-matthias I am looking at this right now, and @gregcaporaso and I were planning on having a meeting about importing on Thursday.

**Comment by bernt-matthias** [comment]
Thanks for letting me know.

**Comment by Oddant1** [comment]
@bernt-matthias thank you for hacking together a functional version of import in current galaxy releases. It appears to be working locally for me. I'll work on integrating it into the q2galaxy code base (also, no one is sorry to see that templated in bit of code go we just didn't know of a better way to achieve our goals at the time, so thank you for getting rid of that).

**Comment by bernt-matthias** [comment]
Note that the `sed` "approach" was just a quick hack. most likely the modifications done to the JSON file should be done in python (either an extra script or maybe directly in `q2galaxy`).

**Comment by Oddant1** [comment]
To be honest, I don't mind the `sed` too much, but all the same I roughed something together within q2galaxy because you're right that is a better idea. #48 addresses a couple of smaller issues I noticed when getting q2galaxy to work with the latest QIIME 2 release and will also most likely be the PR that ends up closing this issue.

**Comment by mvdbeek** [comment]
Changing `type` to `isinstance(obj, MutableMapping)` checks in https://github.com/qiime2/q2galaxy/blob/dev/q2galaxy/core/templaters/import_data.py#L270-L286 should fix it, as we're giving tools a special dict instance that can deal with old tools that don't refer to the complete variable path. I'll see if we can also patch that up in Galaxy or add an exclude for quiime tools. If you want to use the json description of the inputs that's great, but you don't have to.

**Comment by bernt-matthias** [comment]
Can test tomorrow with the tests added here https://github.com/qiime2/galaxy-tools/pull/51

**Comment by Oddant1** [comment]
@bernt-matthias and @mvdbeek: @ebolyen and I met about this today. If we want a quick solution that will get things working right now we can change the `import tool` in https://github.com/qiime2/galaxy-tools to use `sed` and update the version of the tool. If you guys are ok with that, I can have that done later today or tomorrow.

Regardless, we will have a better solution that is internal to q2galaxy and does not require `sed` for the next QIIME 2 release planned to be in mid February. If you guys have made your internal changes by then we will use them if not we will do something else and update to use your internal solution when that is ready.

**Comment by bernt-matthias** [comment]
Let me test the solution that @mvdbeek suggested. Can do this tomorrow. Maybe we can skip the `sed` hack :)

**Comment by Oddant1** [comment]
@mvdbeek's solution requires a change to q2galaxy itself doesn't it? I'm only talking about using `sed` if we need an immediate band-aid to make this work before the next QIIME 2 release because we can edit the tool without updating QIIME 2 or galaxy.

**Comment by bernt-matthias** [comment]
The solution of @mvdbeek seems to work: https://github.com/qiime2/galaxy-tools/pull/51

> requires a change to q2galaxy itself doesn't it? 

It seems that the import tool is the only one using this part of the code. So we could just go with https://github.com/qiime2/galaxy-tools/pull/51, or we implement this in `q2galaxy` .. not sure if needed. Also depends on how you want your release process.

**Comment by Oddant1** [comment]
@bernt-matthias I see what you mean now, I had thought @mvdbeek was talking about making changes elsewhere within q2galaxy. I misunderstood and didn't see the changes he made in qiime2/galaxy-tools#51. His proposed changes there look good to me and do indeed avoid using `sed`

**Comment by Oddant1** [comment]
Later today I am going to test @mvdbeek's solution locally and once I've proven to myself that it works I will patch the tool to use that solution.

When we release the next actual version of QIIME 2 (planned mid February) there will be a solution built into q2galaxy that ought to be more robust.
