### ISSUE TITLE
Running on Apple Silicon M1

### ISSUE THREAD

**Issue by nikothomas** [qiime2/q2galaxy#53]
**Bug Description**
Using the recommended command line input to start an image
`docker run -d -p 8080:80 -p 8021:21 -p 8022:22 -v $HOME/q2galaxy_data/:/export/ quay.io/qiime2/q2galaxy`
results in a warning
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
furthermore it seems to prevent exposure of port 8080 on the localhost.

**Steps to reproduce the behavior**
1.  Follow the docker steps in the README for Docker setup up to the last terminal command.
2. While running macOS on a M1 chip go to terminal.
3. Run `docker run -d -p 8080:80 -p 8021:21 -p 8022:22 -v $HOME/q2galaxy_data/:/export/ quay.io/qiime2/q2galaxy`
4. See error `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Expected behavior**
I expected the docker image to be created successfully.

**Computation Environment**
- OS: [macOS Sonoma 14.1.1]
- QIIME 2 Release [[2024.2.1](https://github.com/qiime2/q2galaxy/releases/tag/2024.2.1)]

**Fix**
1. Run this command to start the container instead (added --platform linux/amd64)
`docker run --platform linux/amd64 -d -p 8080:80 -p 8021:21 -p 8022:22 -v $HOME/q2galaxy_data/:/export/ quay.io/qiime2/q2galaxy`

**References**
1. [Where I found the fix](https://stackoverflow.com/questions/66662820/m1-docker-preview-and-keycloak-images-platform-linux-amd64-does-not-match-th)

**Comment by ebolyen** [comment]
Thanks @nikothomas! I've updated the readme with your suggestion: https://github.com/qiime2/q2galaxy/commit/c837f392bb4ec27cea21f49c53afe5dd8f207826
